#!/bin/bash

if [[ $# -eq 1 ]]; then
    dir=$1
else
    dir=$((find ~/Herd/projects -mindepth 1 -maxdepth 1 -type d && find ~/public_html/projects -mindepth 1 -maxdepth 2 -type d) | fzf)
fi

selected_name=$(basename "$dir" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
